name: Deploy Portfolio Frontend to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Check Build Files
      run: ls -la dist

    - name: Synchronize Files to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "dist/"
        ARGS: "-rlgoDzv -i --delete --exclude=.htaccess"
        REMOTE_HOST: ${{ secrets.VPS_HOST }}
        REMOTE_USER: ${{ secrets.VPS_USER }}
        TARGET: ${{ secrets.FRONTEND_PATH }}

    - name: Confirm Deployment
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Portfolio deployed successfully"
